##
##   Copyright (c) 2020-2022 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##
---
confirmed_skl_cpus:
  # Sky Lake Xeon Gold (quad)
  - "6152"
  # Sky Lake Xeon Platinum (octa)
  - "8176"
confirmed_clx_ncpus:
  - "5218N"
  - "6252N"
  - "6230N"
confirmed_clx_cpus:
  - "6252"

confirmed_icx_cpus:
  - "06/6c"
  - "5318N"
  - "6338"
  - "6338N"
  - "6346"
  - "6348"
  - "8358"
  - "8360Y"
  - "8380"
  - "$0000%@"

confirmed_spr_cpus:
  - "8470N"
  - "8471N"
  - "8490H"
  - "0000%@"

confirmed_adl_cpus:
  - "12800"
